num1 = int(input("Enter 1st no. : "))
num2 = int(input("Enter 2nd no. : "))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** num2)
