length = int(input("Enter length of rectangle : "))
breadth = int(input("Enter breadth of rectangle : "))
perimeter = 2 * (length + breadth)
area = (length * breadth)
print("Perimeter of rectangle : ",perimeter)
print("Area of rectangle : ",area)
